open_graph:
  enable: false
article:
  type: tech
  auto:cover: false
  auto_excerpt: 100
menubar:
  columns: 5
  items: 
    - id: catogories
      theme: ''
      title: 分类
      icon: ''
      url: /categories/

    - id: tags
      theme: ''
      title: 标签
      icon: ''
      url: /tags/

    - id: friends
      theme: ''
      title: 友链
      icon: ''
      url: /friends/

    - id: about
      theme: ''
      title: 我的
      icon: ''
      url: /about/

search:
  service: local_search
  local_search:
    field: all
    path: /search.json
    content: true
    codeblock: true

style:
  prefers_theme: dark
  leftbar:
    background-image: url(https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.13/image/sidebar-bg1@small.jpg)
    blur-px: 100px
    blur-bg: var(--alpha60)

  header_prefix:
    h1: '#'
    h2: '##'
    h3: '###'
    h4: '####'
    h5: '#####'
    h6: '######'
